<script lang="ts">
	import type { ParsedComponent, ForwardedEvent, DispatchedEvent } from './ParsedComponent';
	export let data: ParsedComponent;
	export let manualForward = false;
	const forwardedEvents = <ForwardedEvent[]>data.events.filter((e) => e.type === 'forwarded');
	const dispatchedEvents = <DispatchedEvent[]>data.events.filter((e) => e.type === 'dispatched');
</script>

API docs automatically generated by <a
	href="https://github.com/carbon-design-system/sveld/"
	target="_blank"
	rel="noreffer noopener">sveld</a
>
and
<a href="https://github.com/mattjennings/vite-plugin-sveld/" target="_blank" rel="noreffer noopener"
	>vite-plugin-sveld</a
>.

<h3 id="props">Props</h3>
{#if data.props.length > 0}
	<table>
		<thead>
			<tr class="bg-gray-100 border-b dark:bg-gray-800 dark:border-gray-700 px-3">
				<th
					class="py-3 px-3 text-xs font-medium tracking-wider text-left text-gray-700 uppercase dark:text-gray-400"
					>Name</th
				>
				<th
					class="py-3 px-3 text-xs font-medium tracking-wider text-left text-gray-700 uppercase dark:text-gray-400"
					>Type</th
				>
				<th
					class="py-3 px-3 text-xs font-medium tracking-wider text-left text-gray-700 uppercase dark:text-gray-400"
					>Default</th
				>
				<th
					class="py-3 px-3 text-xs font-medium tracking-wider text-left text-gray-700 uppercase dark:text-gray-400"
					>Description</th
				>
			</tr>
		</thead>
		<tbody>
			{#each data.props as { name, type, value, description }}
				{#if !name.startsWith('__')}
					<tr class="bg-gray-100 border-b dark:bg-gray-800 dark:border-gray-700 px-3">
						<td class="text-sm font-medium text-gray-900 dark:text-white">
							{#if typeof name !== 'undefined'}
								<p>{name}</p>
							{:else}
								Unknown
							{/if}
						</td>
						<td class="text-sm font-medium text-gray-900 dark:text-white">
							{#if typeof type !== 'undefined'}
								<p>{type}</p>
							{:else}
								Unknown
							{/if}
						</td>
						<td class="text-sm font-medium text-gray-900 dark:text-white">
							<p>{value ?? 'undefined'}</p>
						</td>
						<td class="text-sm font-medium text-gray-900 dark:text-white"
							>{description ?? 'None'}</td
						>
					</tr>
				{/if}
			{/each}
		</tbody>
	</table>
{:else}
	None
{/if}

<h3 id="slots">Slots</h3>
{#if data.slots.length > 0}
	<table>
		<thead>
			<tr class="bg-gray-100 border-b dark:bg-gray-800 dark:border-gray-700 px-3">
				<th
					class="py-3 px-3 text-xs font-medium tracking-wider text-left text-gray-700 uppercase dark:text-gray-400"
					>Name</th
				>
				<th
					class="py-3 px-3 text-xs font-medium tracking-wider text-left text-gray-700 uppercase dark:text-gray-400"
					>Slot Props</th
				>
				<th
					class="py-3 px-3 text-xs font-medium tracking-wider text-left text-gray-700 uppercase dark:text-gray-400"
					>Fallback</th
				>
			</tr>
		</thead>
		<tbody>
			{#each data.slots as { name, slot_props, fallback }}
				<tr class="bg-gray-100 border-b dark:bg-gray-800 dark:border-gray-700 px-3">
					<td class="text-sm font-medium text-gray-900 dark:text-white">
						{#if typeof name !== 'undefined'}
							<p>{name === '__default__' ? 'Unnamed (Default)' : name}</p>
						{:else}
							Unknown
						{/if}
					</td>
					<td class="text-sm font-medium text-gray-900 dark:text-white">
						{#if slot_props}
							<p>{slot_props !== '{}' ? slot_props : 'Unknown'}</p>
						{:else}
							None
						{/if}
					</td>
					<td class="text-sm font-medium text-gray-900 dark:text-white">
						{#if typeof fallback !== 'undefined'}
							<p>{fallback.substr(0, 300)}</p>
							{fallback.length > 300 ? '…' : ''}
						{:else}
							Empty
						{/if}
					</td>
				</tr>
			{/each}
		</tbody>
	</table>
{:else}
	None
{/if}

<h3 id="events">Events</h3>
{#if manualForward}
	<h4>Forwarded Events</h4>
	{#if forwardedEvents.length > 0}
		{#each forwardedEvents as { name }}
			<p class="forwarded">
				<a
					href="https://developer.mozilla.org/en-US/docs/Web/API/Element/{name}_event"
					target="_blank"
					rel="noreferrer noopener">{name.trim()}</a
				>
			</p>
		{/each}
	{:else}
		None
	{/if}
{:else}
	<p>
		All DOM events are forwarded to this component's respective elements by default. <a href="#todo"
			>Learn More</a
		>
	</p>
{/if}

<h4>Dispatched Events</h4>
{#if dispatchedEvents.length > 0}
	<table>
		<thead>
			<tr class="bg-gray-100 border-b dark:bg-gray-800 dark:border-gray-700 px-3"
				><th>Name</th><th>Detail</th></tr
			>
		</thead>
		<tbody>
			{#each dispatchedEvents as { name, detail }}
				<tr class="bg-gray-100 border-b dark:bg-gray-800 dark:border-gray-700 px-3">
					<td class="text-sm font-medium text-gray-900 dark:text-white">
						{#if typeof name !== 'undefined'}
							<p>{name}</p>
						{:else}
							Unknown
						{/if}
					</td>
					<td class="text-sm font-medium text-gray-900 dark:text-white">
						{#if typeof detail !== 'undefined'}
							<p>{detail}</p>
						{:else}
							None
						{/if}
					</td>
				</tr>
			{/each}
		</tbody>
	</table>
{:else}
	<p>None</p>
{/if}

<style>
	.forwarded {
		display: inline-flex;
		margin-inline-end: 4px;
		margin-block-end: 4px;
	}
</style>
